version: '3.8'

# Minimal Production Docker Compose Configuration
# מערכת ניהול אומדני עלויות רכש - Production (App + PostgreSQL only)

services:
  # ==============================================================================
  # APPLICATION SERVER
  # ==============================================================================
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
      args:
        - NODE_ENV=production
    container_name: procurement-app
    restart: unless-stopped
    
    # Environment variables
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    
    # Port mapping
    ports:
      - "5000:5000"
    
    # Volume mounts
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/var/log/procurement
      - /etc/localtime:/etc/localtime:ro
    
    # Dependencies
    depends_on:
      postgres:
        condition: service_healthy
    
    # Health check using API endpoint (known to exist)
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000/api/procurement-requests"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # ==============================================================================
  # POSTGRESQL DATABASE
  # ==============================================================================
  postgres:
    image: postgres:15-alpine
    container_name: procurement-postgres
    restart: unless-stopped
    
    # Environment variables
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-procurement_prod}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --locale=C
    
    # Port mapping (internal only)
    expose:
      - "5432"
    
    # Volume mounts
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/var/lib/postgresql/backups
      - /etc/localtime:/etc/localtime:ro
    
    # Health check
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-procurement_prod}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
    
    # PostgreSQL configuration
    command: >
      postgres 
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c work_mem=4MB
      -c min_wal_size=1GB
      -c max_wal_size=4GB
      -c max_connections=100
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# ==============================================================================
# VOLUMES
# ==============================================================================
volumes:
  postgres_data:
    driver: local

# ==============================================================================
# NETWORKS
# ==============================================================================
networks:
  default:
    name: procurement-network
    driver: bridge